### ISSUE TITLE
Present avalanche article as HTML magazine via turn.js

### ISSUE THREAD

**Issue by scottveirs** [ricanddorry/ricanddorry.github.io#11]
Use [turn.js]() to implement an HTML5+javascript "magazine" version of the avalanche article/PDF.

* On OSX, use Preview to manually export each PDF page as a separate jpg file
* This [merge-jpg](https://www.ofoct.com/merge-jpg-files-side-by-side) tool is handy for abutting jpg images side-by-side for the "double-page" layout of turn.js

**Comment by scottveirs** [comment]
Initial solution is now live at [https://ricanddorry.club/content/avalanche/turnjs4/samples/double-page/index.html](https://ricanddorry.club/content/avalanche/turnjs4/samples/double-page/index.html)

**Comment by veirs** [comment]
It took me a bit to find the forward/backward 'buttons' in the upper
corners but with them it is super.
